### ISSUE TITLE
Why this error is happen randomly?

### ISSUE THREAD

**Issue by dobbyjang0** [Bilka2/AbandonedRuins#12] opened 2020-10-15 09:32 UTC
![image](https://user-images.githubusercontent.com/68857611/96100606-8548d100-0f0f-11eb-86c0-e67aad118182.png)

This error happened randomly

I installed Tral's robot Tree farm mods

**Comment by Bilka2** [comment] 2020-10-15 09:40
Please provide a [log file](https://wiki.factorio.com/Log_file) from a session where it crashes like this.

**Comment by dobbyjang0** [comment] 2020-10-15 10:07
Sorry, I can't find logs when the error happens. The problem is solved when I delete Tral's robot Tree farm mods. Maybe it's other mod problems?

**Comment by Bilka2** [comment] 2020-10-15 10:10
Looks like it removes a recipe that should be set on a ruin. I'll close this as a duplicate of #9. Until I fix that you can just remove the tree farm mod to continue playing without crashing.

**Closed as completed by Bilka2** 2020-10-15 10:10 UTC
Labels: bug, duplicate
